// Mocks generated by Mockito 5.4.5 from annotations
// in seller_panel/test/unit/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:seller_panel/features/products/data/datasources/product_firebase_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductFirebaseDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductFirebaseDataSource extends _i1.Mock
    implements _i2.ProductFirebaseDataSource {
  MockProductFirebaseDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getProducts(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [sellerId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [productId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<String> addProduct(Map<String, dynamic>? productData) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [productData]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#addProduct, [productData]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> updateProduct(
    String? productId,
    Map<String, dynamic>? productData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [productId, productData]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> toggleProductAvailability(
    String? productId,
    bool? isAvailable,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleProductAvailability, [
              productId,
              isAvailable,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> uploadProductImages(
    String? productId,
    List<String>? localImagePaths,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProductImages, [
              productId,
              localImagePaths,
            ]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> deleteProductImage(String? productId, String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductImage, [productId, imageUrl]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
