name: root_project

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.3
  flutter_secure_storage: ^9.0.0  
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  shared_models:
    path: shared_modules/shared_models
  shared_services:
    path: shared_modules/shared_services
  shared_widgets:
    path: shared_modules/shared_widgets




dev_dependencies:
  melos: ^6.3.2 # Replace with the latest version if needed
  build_runner: any
  json_serializable: any
  flutter_lints: ^2.0.0  cloud_firestore: any
