// Mocks generated by Mockito 5.4.5 from annotations
// in user_app/test/features/order_tracking/order_tracking_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:location/location.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i6;
import 'package:user_app/features/order_tracking/application/order_tracking_notifier.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrderTrackingState_0 extends _i1.SmartFake
    implements _i2.OrderTrackingState {
  _FakeOrderTrackingState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderTrackingNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderTrackingNotifier extends _i1.Mock
    implements _i2.OrderTrackingNotifier {
  MockOrderTrackingNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i3.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.OrderTrackingState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.OrderTrackingState>.empty(),
      ) as _i4.Stream<_i2.OrderTrackingState>);

  @override
  _i2.OrderTrackingState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeOrderTrackingState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.OrderTrackingState);

  @override
  set state(_i2.OrderTrackingState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.OrderTrackingState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeOrderTrackingState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.OrderTrackingState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> calculateETA(
    _i5.LocationData? deliveryLocation,
    _i5.LocationData? destinationLocation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateETA,
          [
            deliveryLocation,
            destinationLocation,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i2.OrderTrackingState? old,
    _i2.OrderTrackingState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.RemoveListener addListener(
    _i6.Listener<_i2.OrderTrackingState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i3.RemoveListener);
}
