// Mocks generated by Mockito 5.4.5 from annotations
// in user_app/test/features/payment/payment_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i7;
import 'dart:typed_data' as _i9;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter_stripe/src/stripe.dart' as _i10;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:stripe_platform_interface/stripe_platform_interface.dart'
    as _i4;
import 'package:user_app/core/services/secure_storage_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenable_2<T> extends _i1.SmartFake
    implements _i3.ValueListenable<T> {
  _FakeValueListenable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentMethod_3 extends _i1.SmartFake implements _i4.PaymentMethod {
  _FakePaymentMethod_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSetupIntent_4 extends _i1.SmartFake implements _i4.SetupIntent {
  _FakeSetupIntent_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentIntent_5 extends _i1.SmartFake implements _i4.PaymentIntent {
  _FakePaymentIntent_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenData_6 extends _i1.SmartFake implements _i4.TokenData {
  _FakeTokenData_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddToWalletResult_7 extends _i1.SmartFake
    implements _i4.AddToWalletResult {
  _FakeAddToWalletResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFinancialConnectionTokenResult_8 extends _i1.SmartFake
    implements _i4.FinancialConnectionTokenResult {
  _FakeFinancialConnectionTokenResult_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFinancialConnectionSessionResult_9 extends _i1.SmartFake
    implements _i4.FinancialConnectionSessionResult {
  _FakeFinancialConnectionSessionResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i5.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveAuthToken(
    String? token, {
    int? expiryMinutes = 60,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAuthToken,
          [token],
          {#expiryMinutes: expiryMinutes},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getAuthToken() => (super.noSuchMethod(
        Invocation.method(
          #getAuthToken,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> saveRefreshToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> saveUserData(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserData,
          [userData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> savePreferences(Map<String, dynamic>? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreferences,
          [preferences],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getPreferences,
          [],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> saveSecureValue(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSecureValue,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getSecureValue(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getSecureValue,
          [key],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> deleteSecureValue(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteSecureValue,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i9.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i6.Future<_i9.Uint8List>);

  @override
  _i6.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Stripe].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripe extends _i1.Mock implements _i10.Stripe {
  MockStripe() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get debugUpdatePlatformSheetCalled => (super.noSuchMethod(
        Invocation.getter(#debugUpdatePlatformSheetCalled),
        returnValue: false,
      ) as bool);

  @override
  set debugUpdatePlatformSheetCalled(bool? _debugUpdatePlatformSheetCalled) =>
      super.noSuchMethod(
        Invocation.setter(
          #debugUpdatePlatformSheetCalled,
          _debugUpdatePlatformSheetCalled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get debugConfigurePlatformOrderTrackingCalled => (super.noSuchMethod(
        Invocation.getter(#debugConfigurePlatformOrderTrackingCalled),
        returnValue: false,
      ) as bool);

  @override
  set debugConfigurePlatformOrderTrackingCalled(
          bool? _debugConfigurePlatformOrderTrackingCalled) =>
      super.noSuchMethod(
        Invocation.setter(
          #debugConfigurePlatformOrderTrackingCalled,
          _debugConfigurePlatformOrderTrackingCalled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ValueListenable<bool> get isPlatformPaySupportedListenable =>
      (super.noSuchMethod(
        Invocation.getter(#isPlatformPaySupportedListenable),
        returnValue: _FakeValueListenable_2<bool>(
          this,
          Invocation.getter(#isPlatformPaySupportedListenable),
        ),
      ) as _i3.ValueListenable<bool>);

  @override
  _i6.Future<void> applySettings() => (super.noSuchMethod(
        Invocation.method(
          #applySettings,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isPlatformPaySupported(
          {_i4.IsGooglePaySupportedParams? googlePay}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isPlatformPaySupported,
          [],
          {#googlePay: googlePay},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i4.PaymentMethod> createPlatformPayPaymentMethod({
    required _i4.PlatformPayPaymentMethodParams? params,
    bool? usesDeprecatedTokenFlow = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlatformPayPaymentMethod,
          [],
          {
            #params: params,
            #usesDeprecatedTokenFlow: usesDeprecatedTokenFlow,
          },
        ),
        returnValue: _i6.Future<_i4.PaymentMethod>.value(_FakePaymentMethod_3(
          this,
          Invocation.method(
            #createPlatformPayPaymentMethod,
            [],
            {
              #params: params,
              #usesDeprecatedTokenFlow: usesDeprecatedTokenFlow,
            },
          ),
        )),
      ) as _i6.Future<_i4.PaymentMethod>);

  @override
  _i6.Future<_i4.SetupIntent> confirmPlatformPaySetupIntent({
    required String? clientSecret,
    required _i4.PlatformPayConfirmParams? confirmParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPlatformPaySetupIntent,
          [],
          {
            #clientSecret: clientSecret,
            #confirmParams: confirmParams,
          },
        ),
        returnValue: _i6.Future<_i4.SetupIntent>.value(_FakeSetupIntent_4(
          this,
          Invocation.method(
            #confirmPlatformPaySetupIntent,
            [],
            {
              #clientSecret: clientSecret,
              #confirmParams: confirmParams,
            },
          ),
        )),
      ) as _i6.Future<_i4.SetupIntent>);

  @override
  _i6.Future<_i4.PaymentIntent> confirmPlatformPayPaymentIntent({
    required String? clientSecret,
    required _i4.PlatformPayConfirmParams? confirmParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPlatformPayPaymentIntent,
          [],
          {
            #clientSecret: clientSecret,
            #confirmParams: confirmParams,
          },
        ),
        returnValue: _i6.Future<_i4.PaymentIntent>.value(_FakePaymentIntent_5(
          this,
          Invocation.method(
            #confirmPlatformPayPaymentIntent,
            [],
            {
              #clientSecret: clientSecret,
              #confirmParams: confirmParams,
            },
          ),
        )),
      ) as _i6.Future<_i4.PaymentIntent>);

  @override
  _i6.Future<void> updatePlatformSheet(
          {required _i4.PlatformPaySheetUpdateParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlatformSheet,
          [],
          {#params: params},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> configurePlatformOrderTracking(
          {required _i4.PlatformPayOrderDetails? orderDetails}) =>
      (super.noSuchMethod(
        Invocation.method(
          #configurePlatformOrderTracking,
          [],
          {#orderDetails: orderDetails},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.TokenData> createApplePayToken(
          Map<String, dynamic>? payment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createApplePayToken,
          [payment],
        ),
        returnValue: _i6.Future<_i4.TokenData>.value(_FakeTokenData_6(
          this,
          Invocation.method(
            #createApplePayToken,
            [payment],
          ),
        )),
      ) as _i6.Future<_i4.TokenData>);

  @override
  _i6.Future<_i4.PaymentMethod> createPaymentMethod({
    required _i4.PaymentMethodParams? params,
    _i4.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPaymentMethod,
          [],
          {
            #params: params,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.PaymentMethod>.value(_FakePaymentMethod_3(
          this,
          Invocation.method(
            #createPaymentMethod,
            [],
            {
              #params: params,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.PaymentMethod>);

  @override
  _i6.Future<_i4.TokenData> createToken(_i4.CreateTokenParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createToken,
          [params],
        ),
        returnValue: _i6.Future<_i4.TokenData>.value(_FakeTokenData_6(
          this,
          Invocation.method(
            #createToken,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.TokenData>);

  @override
  _i6.Future<_i4.PaymentIntent> retrievePaymentIntent(String? clientSecret) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrievePaymentIntent,
          [clientSecret],
        ),
        returnValue: _i6.Future<_i4.PaymentIntent>.value(_FakePaymentIntent_5(
          this,
          Invocation.method(
            #retrievePaymentIntent,
            [clientSecret],
          ),
        )),
      ) as _i6.Future<_i4.PaymentIntent>);

  @override
  _i6.Future<_i4.SetupIntent> retrieveSetupIntent(String? clientSecret) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveSetupIntent,
          [clientSecret],
        ),
        returnValue: _i6.Future<_i4.SetupIntent>.value(_FakeSetupIntent_4(
          this,
          Invocation.method(
            #retrieveSetupIntent,
            [clientSecret],
          ),
        )),
      ) as _i6.Future<_i4.SetupIntent>);

  @override
  _i6.Future<void> openApplePaySetup() => (super.noSuchMethod(
        Invocation.method(
          #openApplePaySetup,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> handleURLCallback(String? url) => (super.noSuchMethod(
        Invocation.method(
          #handleURLCallback,
          [url],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i4.PaymentIntent> confirmPayment({
    required String? paymentIntentClientSecret,
    _i4.PaymentMethodParams? data,
    _i4.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentIntentClientSecret: paymentIntentClientSecret,
            #data: data,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.PaymentIntent>.value(_FakePaymentIntent_5(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentIntentClientSecret: paymentIntentClientSecret,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.PaymentIntent>);

  @override
  _i6.Future<_i4.PaymentIntent> handleNextAction(
    String? paymentIntentClientSecret, {
    String? returnURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleNextAction,
          [paymentIntentClientSecret],
          {#returnURL: returnURL},
        ),
        returnValue: _i6.Future<_i4.PaymentIntent>.value(_FakePaymentIntent_5(
          this,
          Invocation.method(
            #handleNextAction,
            [paymentIntentClientSecret],
            {#returnURL: returnURL},
          ),
        )),
      ) as _i6.Future<_i4.PaymentIntent>);

  @override
  _i6.Future<_i4.SetupIntent> handleNextActionForSetupIntent(
    String? setupIntentClientSecret, {
    String? returnURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleNextActionForSetupIntent,
          [setupIntentClientSecret],
          {#returnURL: returnURL},
        ),
        returnValue: _i6.Future<_i4.SetupIntent>.value(_FakeSetupIntent_4(
          this,
          Invocation.method(
            #handleNextActionForSetupIntent,
            [setupIntentClientSecret],
            {#returnURL: returnURL},
          ),
        )),
      ) as _i6.Future<_i4.SetupIntent>);

  @override
  _i6.Future<_i4.SetupIntent> confirmSetupIntent({
    required String? paymentIntentClientSecret,
    required _i4.PaymentMethodParams? params,
    _i4.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSetupIntent,
          [],
          {
            #paymentIntentClientSecret: paymentIntentClientSecret,
            #params: params,
            #options: options,
          },
        ),
        returnValue: _i6.Future<_i4.SetupIntent>.value(_FakeSetupIntent_4(
          this,
          Invocation.method(
            #confirmSetupIntent,
            [],
            {
              #paymentIntentClientSecret: paymentIntentClientSecret,
              #params: params,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i4.SetupIntent>);

  @override
  _i6.Future<String?> createTokenForCVCUpdate(String? cvc) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTokenForCVCUpdate,
          [cvc],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i4.PaymentSheetPaymentOption?> initPaymentSheet(
          {required _i4.SetupPaymentSheetParameters? paymentSheetParameters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initPaymentSheet,
          [],
          {#paymentSheetParameters: paymentSheetParameters},
        ),
        returnValue: _i6.Future<_i4.PaymentSheetPaymentOption?>.value(),
      ) as _i6.Future<_i4.PaymentSheetPaymentOption?>);

  @override
  _i6.Future<_i4.PaymentSheetPaymentOption?> presentPaymentSheet(
          {_i4.PaymentSheetPresentOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentPaymentSheet,
          [],
          {#options: options},
        ),
        returnValue: _i6.Future<_i4.PaymentSheetPaymentOption?>.value(),
      ) as _i6.Future<_i4.PaymentSheetPaymentOption?>);

  @override
  _i6.Future<void> intentCreationCallback(
          _i4.IntentCreationCallbackParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #intentCreationCallback,
          [params],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetPaymentSheetCustomer() => (super.noSuchMethod(
        Invocation.method(
          #resetPaymentSheetCustomer,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> confirmPaymentSheetPayment() => (super.noSuchMethod(
        Invocation.method(
          #confirmPaymentSheetPayment,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dangerouslyUpdateCardDetails(_i4.CardDetails? card) =>
      (super.noSuchMethod(
        Invocation.method(
          #dangerouslyUpdateCardDetails,
          [card],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> initGooglePay(_i4.GooglePayInitParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #initGooglePay,
          [params],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> presentGooglePay(_i4.PresentGooglePayParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentGooglePay,
          [params],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.PaymentMethod> createGooglePayPaymentMethod(
          _i4.CreateGooglePayPaymentParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGooglePayPaymentMethod,
          [params],
        ),
        returnValue: _i6.Future<_i4.PaymentMethod>.value(_FakePaymentMethod_3(
          this,
          Invocation.method(
            #createGooglePayPaymentMethod,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.PaymentMethod>);

  @override
  _i6.Future<bool> isGooglePaySupported(
          _i4.IsGooglePaySupportedParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #isGooglePaySupported,
          [params],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i4.PaymentIntent> collectBankAccount({
    required bool? isPaymentIntent,
    required String? clientSecret,
    required _i4.CollectBankAccountParams? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectBankAccount,
          [],
          {
            #isPaymentIntent: isPaymentIntent,
            #clientSecret: clientSecret,
            #params: params,
          },
        ),
        returnValue: _i6.Future<_i4.PaymentIntent>.value(_FakePaymentIntent_5(
          this,
          Invocation.method(
            #collectBankAccount,
            [],
            {
              #isPaymentIntent: isPaymentIntent,
              #clientSecret: clientSecret,
              #params: params,
            },
          ),
        )),
      ) as _i6.Future<_i4.PaymentIntent>);

  @override
  _i6.Future<_i4.PaymentIntent> verifyPaymentIntentWithMicrodeposits({
    required bool? isPaymentIntent,
    required String? clientSecret,
    required _i4.VerifyMicroDepositsParams? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPaymentIntentWithMicrodeposits,
          [],
          {
            #isPaymentIntent: isPaymentIntent,
            #clientSecret: clientSecret,
            #params: params,
          },
        ),
        returnValue: _i6.Future<_i4.PaymentIntent>.value(_FakePaymentIntent_5(
          this,
          Invocation.method(
            #verifyPaymentIntentWithMicrodeposits,
            [],
            {
              #isPaymentIntent: isPaymentIntent,
              #clientSecret: clientSecret,
              #params: params,
            },
          ),
        )),
      ) as _i6.Future<_i4.PaymentIntent>);

  @override
  _i6.Future<_i4.AddToWalletResult> canAddToWallet(String? last4) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAddToWallet,
          [last4],
        ),
        returnValue:
            _i6.Future<_i4.AddToWalletResult>.value(_FakeAddToWalletResult_7(
          this,
          Invocation.method(
            #canAddToWallet,
            [last4],
          ),
        )),
      ) as _i6.Future<_i4.AddToWalletResult>);

  @override
  _i6.Future<_i4.FinancialConnectionTokenResult> collectBankAccountToken(
          {required String? clientSecret}) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectBankAccountToken,
          [],
          {#clientSecret: clientSecret},
        ),
        returnValue: _i6.Future<_i4.FinancialConnectionTokenResult>.value(
            _FakeFinancialConnectionTokenResult_8(
          this,
          Invocation.method(
            #collectBankAccountToken,
            [],
            {#clientSecret: clientSecret},
          ),
        )),
      ) as _i6.Future<_i4.FinancialConnectionTokenResult>);

  @override
  _i6.Future<_i4.FinancialConnectionSessionResult>
      collectFinancialConnectionsAccounts({required String? clientSecret}) =>
          (super.noSuchMethod(
            Invocation.method(
              #collectFinancialConnectionsAccounts,
              [],
              {#clientSecret: clientSecret},
            ),
            returnValue: _i6.Future<_i4.FinancialConnectionSessionResult>.value(
                _FakeFinancialConnectionSessionResult_9(
              this,
              Invocation.method(
                #collectFinancialConnectionsAccounts,
                [],
                {#clientSecret: clientSecret},
              ),
            )),
          ) as _i6.Future<_i4.FinancialConnectionSessionResult>);

  @override
  _i6.Future<_i4.CustomerSheetResult?> initCustomerSheet(
          {required _i4.CustomerSheetInitParams? customerSheetInitParams}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initCustomerSheet,
          [],
          {#customerSheetInitParams: customerSheetInitParams},
        ),
        returnValue: _i6.Future<_i4.CustomerSheetResult?>.value(),
      ) as _i6.Future<_i4.CustomerSheetResult?>);

  @override
  _i6.Future<_i4.CustomerSheetResult?> presentCustomerSheet(
          {_i4.CustomerSheetPresentParams? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentCustomerSheet,
          [],
          {#options: options},
        ),
        returnValue: _i6.Future<_i4.CustomerSheetResult?>.value(),
      ) as _i6.Future<_i4.CustomerSheetResult?>);

  @override
  _i6.Future<_i4.CustomerSheetResult?>
      retrieveCustomerSheetPaymentOptionSelection() => (super.noSuchMethod(
            Invocation.method(
              #retrieveCustomerSheetPaymentOptionSelection,
              [],
            ),
            returnValue: _i6.Future<_i4.CustomerSheetResult?>.value(),
          ) as _i6.Future<_i4.CustomerSheetResult?>);

  @override
  void markNeedsSettings() => super.noSuchMethod(
        Invocation.method(
          #markNeedsSettings,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
