// Mocks generated by Mockito 5.4.5 from annotations
// in user_app/test/features/cart/domain/usecases/cart_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:user_app/core/architecture/domain/failure.dart' as _i5;
import 'package:user_app/features/cart/domain/entities/cart_item.dart' as _i6;
import 'package:user_app/features/cart/domain/repositories/cart_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i3.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CartItem>>> getCartItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartItems,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.CartItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CartItem>>(
          this,
          Invocation.method(
            #getCartItems,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CartItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>> addCartItem(
          _i6.CartItem? cartItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCartItem,
          [cartItem],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>.value(
            _FakeEither_0<_i5.Failure, _i6.CartItem>(
          this,
          Invocation.method(
            #addCartItem,
            [cartItem],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>> updateCartItem(
          _i6.CartItem? cartItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartItem,
          [cartItem],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>.value(
            _FakeEither_0<_i5.Failure, _i6.CartItem>(
          this,
          Invocation.method(
            #updateCartItem,
            [cartItem],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CartItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeCartItem(
          String? cartItemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [cartItemId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeCartItem,
            [cartItemId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearCart() => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #clearCart,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getCartItemsCount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartItemsCount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getCartItemsCount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, double>> getCartTotal() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartTotal,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, double>>.value(
            _FakeEither_0<_i5.Failure, double>(
          this,
          Invocation.method(
            #getCartTotal,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, double>>);
}
