// Mocks generated by Mockito 5.4.5 from annotations
// in user_app/test/features/ratings/ratings_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i5;
import 'package:user_app/features/ratings/application/ratings_notifier.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAsyncValue_0<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RatingsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingsNotifier extends _i1.Mock implements _i3.RatingsNotifier {
  MockRatingsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i2.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.AsyncValue<List<_i3.RatingModel>>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.AsyncValue<List<_i3.RatingModel>>>.empty(),
      ) as _i4.Stream<_i2.AsyncValue<List<_i3.RatingModel>>>);

  @override
  _i2.AsyncValue<List<_i3.RatingModel>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_0<List<_i3.RatingModel>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<List<_i3.RatingModel>>);

  @override
  set state(_i2.AsyncValue<List<_i3.RatingModel>>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AsyncValue<List<_i3.RatingModel>> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeAsyncValue_0<List<_i3.RatingModel>>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.AsyncValue<List<_i3.RatingModel>>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadUserRatings() => (super.noSuchMethod(
        Invocation.method(
          #loadUserRatings,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRating({
    required String? targetId,
    required String? targetType,
    required double? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRating,
          [],
          {
            #targetId: targetId,
            #targetType: targetType,
            #rating: rating,
            #comment: comment,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRating(String? ratingId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRating,
          [ratingId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<List<_i3.RatingModel>>? old,
    _i2.AsyncValue<List<_i3.RatingModel>>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.RemoveListener addListener(
    _i5.Listener<_i2.AsyncValue<List<_i3.RatingModel>>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i2.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
