import 'package:flutter/material.dart';
import 'package:admin_panell/router.dart';
import 'package:admin_panell/theme.dart'; // Assuming theme.dart exists
import 'package:flutter_riverpod/flutter_riverpod.dart'; // Import Riverpod
// Import Firebase Core
// Import firebase_options.dart (Ensure this file is generated by FlutterFire CLI)
// import 'firebase_options.dart'; // Commented out: File does not exist yet

Future<void> main() async { // Make main async
   WidgetsFlutterBinding.ensureInitialized();
   // Initialize Firebase 
   // Commented out until firebase_options.dart is generated
   // await Firebase.initializeApp(
   //   options: DefaultFirebaseOptions.currentPlatform, 
   // );
   runApp(const ProviderScope(child: AdminPanelApp())); // Wrap with ProviderScope
 }

class AdminPanelApp extends StatelessWidget {
  const AdminPanelApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Admin Panel', // Consider using AdminConstants.appTitle
      theme: AppTheme.lightTheme, // Use theme from theme.dart
      darkTheme: AppTheme.darkTheme, // Optional dark theme
      themeMode: ThemeMode.system, // Or ThemeMode.light / ThemeMode.dark
      routerConfig: appRouter, // Use the router configuration
    );
  }
}
